In [16]:
data = np.array([
    [7, 1, 5],
    [8, 4, 5],
    [2, 9, 3]
])
a=np.sort(data, axis=0)
b=a.T
c=np.hstack((a, b))
d=np.vstack((a, b))
e=np.concatenate((a, b), axis=None)

print('отсортированные столбцы: ', '\n', a)
print('транспонированный массив: ', '\n', b)
print('горизонтальное объединение: ', '\n', c)
print('вертикальное объединение: ', '\n', d)
print('объединение без оси: ', '\n', e)

отсортированные столбцы:  
 [[2 1 3]
 [7 4 5]
 [8 9 5]]
транспонированный массив:  
 [[2 7 8]
 [1 4 9]
 [3 5 5]]
горизонтальное объединение:  
 [[2 1 3 2 7 8]
 [7 4 5 1 4 9]
 [8 9 5 3 5 5]]
вертикальное объединение:  
 [[2 1 3]
 [7 4 5]
 [8 9 5]
 [2 7 8]
 [1 4 9]
 [3 5 5]]
объединение без оси:  
 [2 1 3 7 4 5 8 9 5 2 7 8 1 4 9 3 5 5]


In [7]:
import numpy as np
import math as m
def what_type(a):
    if np.amin(a) < 0:
        if abs(np.amax(a)) < abs(np.amin(a)):
            eltype=m.ceil(np.log(abs(np.amin(a)))/np.log(2))
        else:
            eltype=m.ceil(np.log(np.amax(a))/np.log(2))
        dtype=np.int8
    else:
        eltype=m.ceil(np.log(np.amax(a))/np.log(2))
        if eltype<11:
            dtype=np.uint8
        else:
            dtype=np.uint64
    return dtype

n=int(input())
a=[]
for i in range (n):      
    a.append(int(input()))
dtype=what_type(a)
row = np.array(a, dtype=dtype)
print(row)

2
5
6
[5 6]


In [9]:
import numpy as np

data_file=[]
with open("Cell_culture.txt") as f:
    for line in f:
        data_file.append (tuple([str(x) for x in line.split('\t')]))
        
cell_data=[]   
cell_data = np.array([data_file
], dtype=[("date", str, 10), ("name", str, 10), ("volume", int), ("comment", str, 20)])

print('заказанное количество на 5 апрел:', sum(cell_data[cell_data["date"] =='5-Apr']["volume"]))
print('имена заказчиков на 9 апреля:', cell_data[cell_data["date"] == '9-Apr']["name"])



заказанное количество на 5 апрел: 343
имена заказчиков на 9 апреля: ['Dasha' 'Liza']
